/**
 * Deployment Guide Generator Plugin — Generates deployment documentation
 */
import fs from 'node:fs';
import path from 'node:path';
import { createChildLogger } from '../../../_shared/logger.js';
import { nowISO } from '../../../_shared/utils.js';

const log = createChildLogger('plugin:deploy-guide');

export interface DeployPrerequisite {
  name: string;
  version?: string;
  installCmd?: string;
}

export interface DeployStep {
  title: string;
  commands?: string[];
  description?: string;
}

export interface DeployGuideInput {
  projectName: string;
  description?: string;
  prerequisites?: DeployPrerequisite[];
  envVars?: { name: string; description: string; required: boolean; example?: string }[];
  setupSteps?: DeployStep[];
  runSteps?: DeployStep[];
  healthCheck?: { url: string; expectedStatus: number };
  ports?: { port: number; description: string }[];
  troubleshooting?: { problem: string; solution: string }[];
}

export class DeployGuideGeneratorPlugin {
  readonly name = 'deploy-guide-generator';
  readonly type = 'generator' as const;

  generate(input: DeployGuideInput, outputDir: string): string {
    const sections: string[] = [];

    // Header
    sections.push(
      `# ${input.projectName} — Deployment Guide`,
      '',
      `> Generated: ${nowISO().slice(0, 10)}`,
      '',
    );

    if (input.description) {
      sections.push(input.description, '');
    }

    // Prerequisites
    if (input.prerequisites?.length) {
      sections.push('## Prerequisites', '');
      sections.push('| Tool | Version | Install |');
      sections.push('|------|---------|---------|');
      for (const p of input.prerequisites) {
        sections.push(`| ${p.name} | ${p.version ?? '-'} | ${p.installCmd ? `\`${p.installCmd}\`` : '-'} |`);
      }
      sections.push('');
    }

    // Environment variables
    if (input.envVars?.length) {
      sections.push('## Environment Variables', '');
      sections.push('| Variable | Description | Required | Example |');
      sections.push('|----------|-------------|----------|---------|');
      for (const v of input.envVars) {
        sections.push(`| \`${v.name}\` | ${v.description} | ${v.required ? 'Yes' : 'No'} | ${v.example ? `\`${v.example}\`` : '-'} |`);
      }
      sections.push('', 'Copy `.env.example` to `.env` and fill in values:', '');
      sections.push('```bash', 'cp .env.example .env', '```', '');
    }

    // Setup
    if (input.setupSteps?.length) {
      sections.push('## Setup', '');
      for (let i = 0; i < input.setupSteps.length; i++) {
        const step = input.setupSteps[i];
        sections.push(`### ${i + 1}. ${step.title}`, '');
        if (step.description) sections.push(step.description, '');
        if (step.commands?.length) {
          sections.push('```bash');
          for (const cmd of step.commands) sections.push(cmd);
          sections.push('```', '');
        }
      }
    }

    // Run
    if (input.runSteps?.length) {
      sections.push('## Running', '');
      for (const step of input.runSteps) {
        sections.push(`### ${step.title}`, '');
        if (step.description) sections.push(step.description, '');
        if (step.commands?.length) {
          sections.push('```bash');
          for (const cmd of step.commands) sections.push(cmd);
          sections.push('```', '');
        }
      }
    }

    // Ports
    if (input.ports?.length) {
      sections.push('## Ports', '');
      sections.push('| Port | Description |');
      sections.push('|------|-------------|');
      for (const p of input.ports) {
        sections.push(`| ${p.port} | ${p.description} |`);
      }
      sections.push('');
    }

    // Health check
    if (input.healthCheck) {
      sections.push('## Health Check', '');
      sections.push('```bash');
      sections.push(`curl -s ${input.healthCheck.url} | jq .`);
      sections.push('```', '');
      sections.push(`Expected HTTP status: \`${input.healthCheck.expectedStatus}\``, '');
    }

    // Troubleshooting
    if (input.troubleshooting?.length) {
      sections.push('## Troubleshooting', '');
      for (const t of input.troubleshooting) {
        sections.push(`**${t.problem}**`, '');
        sections.push(t.solution, '');
      }
    }

    sections.push('---', '*Auto-generated by Nanoprym Deploy Guide Generator*', '');

    const content = sections.join('\n');

    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
    const filePath = path.join(outputDir, 'DEPLOYMENT.md');
    fs.writeFileSync(filePath, content);
    log.info('Deployment guide generated', { project: input.projectName, file: filePath });
    return filePath;
  }
}
