/**
 * ADR Generator Plugin — Architecture Decision Records
 */
import fs from 'node:fs';
import path from 'node:path';
import { createChildLogger } from '../../../_shared/logger.js';
import { nowISO } from '../../../_shared/utils.js';

const log = createChildLogger('plugin:adr');

export interface ADRInput {
  title: string;
  context: string;
  decision: string;
  consequences: string[];
  alternatives?: string[];
  status?: 'proposed' | 'accepted' | 'deprecated' | 'superseded';
}

export class ADRGeneratorPlugin {
  readonly name = 'adr-generator';
  readonly type = 'generator' as const;

  generate(input: ADRInput, outputDir: string): string {
    // Find next ADR number
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
    const existing = fs.readdirSync(outputDir).filter(f => f.match(/^ADR-\d+/));
    const nextNum = existing.length + 1;
    const slug = input.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50);
    const filename = `ADR-${String(nextNum).padStart(4, '0')}-${slug}.md`;
    const filePath = path.join(outputDir, filename);

    const content = [
      `# ADR-${String(nextNum).padStart(4, '0')}: ${input.title}`,
      '',
      `**Status**: ${input.status ?? 'accepted'}`,
      `**Date**: ${nowISO().slice(0, 10)}`,
      '',
      '## Context',
      input.context,
      '',
      '## Decision',
      input.decision,
      '',
      ...(input.alternatives?.length ? [
        '## Alternatives Considered',
        ...input.alternatives.map(a => `- ${a}`),
        '',
      ] : []),
      '## Consequences',
      ...input.consequences.map(c => `- ${c}`),
      '',
      '---',
      '*Auto-generated by Nanoprym ADR Generator*',
    ].join('\n');

    fs.writeFileSync(filePath, content);
    log.info('ADR generated', { number: nextNum, file: filename });
    return filePath;
  }
}
