/**
 * RCA Generator Plugin — Root Cause Analysis for bug fixes
 * Auto-generates RCA docs when a DEBUG task completes successfully.
 */
import fs from 'node:fs';
import path from 'node:path';
import { createChildLogger } from '../../../_shared/logger.js';
import { nowISO } from '../../../_shared/utils.js';

const log = createChildLogger('plugin:rca-generator');

export interface RCAInput {
  taskId: string;
  issueTitle: string;
  issueDescription: string;
  rootCause: string;
  fix: string;
  filesChanged: string[];
  preventionSteps: string[];
}

export class RCAGeneratorPlugin {
  readonly name = 'rca-generator';
  readonly type = 'generator' as const;

  generate(input: RCAInput, outputDir: string): string {
    const filename = `RCA-${input.taskId.slice(0, 8)}.md`;
    const filePath = path.join(outputDir, filename);

    const content = [
      `# Root Cause Analysis: ${input.issueTitle}`,
      '',
      `**Date**: ${nowISO().slice(0, 10)}`,
      `**Task ID**: ${input.taskId}`,
      '',
      '## Issue',
      input.issueDescription,
      '',
      '## Root Cause',
      input.rootCause,
      '',
      '## Fix Applied',
      input.fix,
      '',
      '## Files Changed',
      ...input.filesChanged.map(f => `- ${f}`),
      '',
      '## Prevention',
      ...input.preventionSteps.map(s => `- ${s}`),
      '',
      '---',
      '*Auto-generated by Nanoprym RCA Generator*',
    ].join('\n');

    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(filePath, content);
    log.info('RCA generated', { taskId: input.taskId, file: filename });
    return filePath;
  }
}
